### ISSUE TITLE
Which branch to use in SBT

### ISSUE THREAD

**Issue by slentzen** [ktakagaki/breeze#15]
Which branch should I rely on as a managed dependency when using SBT to rely on git@github.com:ktakagaki/nounou.git instead of the unmanaged jar in /lib?

Would also like to add .idea/ to .gitignore in all future projects. It really has a dramatic impact on build compatability. Will use SBT gen-idea instead.

@ktakagaki

**Comment by ktakagaki** [comment]
https://github.com/ktakagaki/breeze/tree/nounou

so I guess something like
`````
git@github.com:ktakagaki/breeze.git[[[whateverSyntaxGetsYouToBranch"nounou"]]
`````

**Comment by slentzen** [comment]
Yup. But question is, should I base it on the master branch, or another branch. There are really a large number of branches and they all sounds like they could be relevant.

**Comment by ktakagaki** [comment]
As I wrote, the "nounou" branch (of ktakagaki/breeze)


*Kentaroh Takagaki, MD PhD (高垣 堅太郎)*
     Group Leader, AG Neuro-Optics
     Department Systems Physiology of Learning
     Leibniz Institute for Neurobiology
     <kentaroh.takagaki@lin-magdeburg.de
<kentaroh.takagaki@ifn-magdeburg.de>>
     http://www.lin-magdeburg.de/en/ifn_mp.jsp?member=ktakagak&fc=T
